# Railway Deployment Configuration
# This file tells Railway how to deploy your backend

[build]
  command = "npm install"

[deploy]
  startCommand = "npm start"

[env]
  PORT = "5000"
  NODE_ENV = "production"
